export DJANGO_SECRET_KEY='123'
export G_PRIVATE_KEY=test
export G_TYPE=service_account
export G_CLIENT_EMAIL=test
export G_PRIVATE_KEY_ID=test
export G_CLIENT_ID=test
export G_PROJECT_ID=test
export G_AUTH_URI=test
export G_TOKEN_URI=test
export G_AUTH_PROVIDER_X509_CERT_URL=test
export G_CLIENT_X509_CERT_URL=test
./manage.py runserver 0.0.0.0:4000 --settings=settings.dev
