# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElvantoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Group Name')),
                ('e_id', models.CharField(max_length=36, verbose_name='Elvanto ID')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Google Email')),
                ('last_pulled', models.DateTimeField(blank=True, null=True)),
                ('last_pushed', models.DateTimeField(blank=True, null=True)),
                ('push_auto', models.BooleanField(default=False, help_text='Check this if you want changes for this group to be pushed to google periodically', verbose_name='Auto Push?')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElvantoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=36, verbose_name='Elvanto ID')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('first_name', models.CharField(max_length=250, verbose_name='First Name')),
                ('preferred_name', models.CharField(blank=True, max_length=250, verbose_name='Preferred Name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last Name')),
                ('disabled_entirely', models.BooleanField(default=False)),
                ('disabled_groups', models.ManyToManyField(blank=True, related_name='group_members_disabled', to='elvanto_sync.ElvantoGroup')),
                ('elvanto_groups', models.ManyToManyField(blank=True, related_name='group_members', to='elvanto_sync.ElvantoGroup')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
